---
# tasks file for roles/install-and-configure-external-docker-registry
- name: Get Host Facts
  setup:

- name: Set Registry hostname if not set already
  set_fact:
    registry_host_fqdn: "{{ ansible_fqdn }}"
  when:
    - not registry_host_fqdn is defined or (registry_host_fqdn is defined and registry_host_fqdn == '')
  
- name: Ensure the Cert file does not already exist
  stat:
    path: registry_certfile
  register: cert_exist

- name: Import tasks to secure registry
  vars:
    cert_exist: "{{ cert_exist }}"
  include_tasks: secure-registry.yml 
  when: 
    - secure_registry | bool

- name: Import tasks to create self signed certificate 
  include_tasks: generate-registry-certificate.yml
  when: 
    - secure_registry | bool
    - cert_exist is defined 
    - not cert_exist.stat.exists

- name: Import tasks to create Authentication file for Registry
  include_tasks: generate-registry-authentication.yml 
  when:
    - enable_authz_on_registry is defined and enable_authz_on_registry | bool
    - registry_admin_username is defined and registry_admin_username | length > 0
    - registry_admin_password is defined and registry_admin_password | length > 0

- name: Import tasks to install RPM based registry
  include_tasks: deploy-rpm-registry.yml
  when: 
    - not use_containeried_registry is defined or not use_containeried_registry | bool

- name: Import tasks to install containerized registry
  include_tasks: deploy-containerized-registry.yml
  when: 
    - use_containeried_registry is defined
    - use_containeried_registry | bool

- name: Import tasks to import registry certificate into bastion
  include_tasks: fetch-registry-certs.yml 
  when: 
    - secure_registry | bool
    - cert_exist is defined 
    - cert_exist.stat.exists
