- name: Create Certificate directory
  file:
    state: directory
    path: "{{ registry_certs_dir }}"
    mode: 0755
    owner: root
    group: root
  when:
    - registry_certs_dir is defined and registry_certs_dir | length > 0 

- name: Copy certifcate to directory created above
  copy:
    remote_src: yes
    src: "{{ registry_certfile }}"
    dest: "{{ registry_certs_dir }}"
  when: 
    - registry_certfile is defined and registry_certfile | length > 0
