- name: Create Registry Certificate directory
  file:
    state: directory
    path: "{{ registry_certs_dir }}"
    mode: 0755
    owner: root
    group: root
    recurse: yes
  when:
    - registry_certs_dir is defined and not registry_certs_dir == '' 

- name: Create Registry Data  directory
  file:
    state: directory
    path: "{{ registry_data_dir }}"
    mode: 0755
    owner: root
    group: root
    recurse: yes
  when:
    - registry_data_dir is defined and not registry_data_dir == '' 

- name: Create Registry Auth directory
  file:
    state: directory
    path: "{{ registry_auth_dir }}"
    mode: 0755
    owner: root
    group: root
    recurse: yes
  when:
    - registry_auth_dir is defined and not registry_auth_dir == '' 

- name: Copy certifcate to directory created above
  copy:
    remote_src: yes
    src: "{{ registry_certfile }}"
    dest: "{{ registry_certs_dir }}/{{ registry_certfile | basename }}"
  when: 
    - not generate_selfsigned_registry_certfiles is defined or not generate_selfsigned_registry_certfiles | bool 
    - registry_certfile is defined and not registry_certfile == ''
